function BodyStress = BodyStress(X,Y)
%BODYSTRESS
%    BODYSTRESS = BODYSTRESS(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Mar-2022 21:49:56

BodyStress = [2.5e+1./1.3e+1;2.5e+1./1.3e+1;0.0];
