function BodyStress = BodyStress(X,Y)
%BODYSTRESS
%    BODYSTRESS = BODYSTRESS(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Mar-2022 22:43:45

t2 = X.*pi;
t3 = Y.*pi;
t4 = cos(t2);
t5 = cos(t3);
t6 = sin(t3);
BodyStress = [t4.*pi.*(t5.*3.0+t6.*7.0).*(5.0./2.6e+1);t4.*pi.*(t5.*7.0+t6.*3.0).*(5.0./2.6e+1);sqrt(2.0).*pi.*cos((pi.*(Y.*4.0+1.0))./4.0).*sin(t2).*(5.0./1.3e+1)];
