function BodyForce = BodyForce(X,Y)
%BODYFORCE
%    BODYFORCE = BODYFORCE(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Mar-2022 21:49:56

BodyForce = [0.0;0.0];
