function ImposedDisplacements = ImposedDisplacements(X,Y)
%IMPOSEDDISPLACEMENTS
%    IMPOSEDDISPLACEMENTS = IMPOSEDDISPLACEMENTS(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Mar-2022 21:49:56

ImposedDisplacements = [X;Y];
