function ImposedDisplacements = ImposedDisplacements(X,Y)
%IMPOSEDDISPLACEMENTS
%    IMPOSEDDISPLACEMENTS = IMPOSEDDISPLACEMENTS(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Mar-2022 22:43:45

t2 = X.*pi;
t3 = Y.*pi;
t4 = sin(t3);
ImposedDisplacements = [t4.*sin(t2);t4.*cos(t2)];
